DROP TABLE IF EXISTS stats CASCADE;

-- Create the stats table
CREATE TABLE stats (
    id SERIAL PRIMARY KEY NOT NULL,
    hp INTEGER NOT NULL DEFAULT 10,
    atk INTEGER NOT NULL DEFAULT 1,
    def INTEGER NOT NULL DEFAULT 1,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);